#!/usr/bin/env bash

if [[ "$(uname)" == "Ubuntu" ]]; then
    echo "Installing for Ubuntu"
    chmod +x ./ubuntu && ./ubuntu
fi

if [[ "$(uname)" == "Darwin" ]]; then
    echo "Installing for MacOS"
    chmod +x ./macos && ./macos
fi

