- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    username: "james"
  pre_tasks:
    - name: Update Apt (only for Ubuntu)
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      when: ansible_facts.distribution == "Ubuntu"
      tags:
        - install
        - core

  tasks:
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/mise.yml
