- hosts: localhost
  vars:
    source_key: ./.ssh/personal
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/personal"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    username: "james"
  pre_tasks:
    - name: Remove conflicting CUDA repository configurations
      file:
        path: "{{ item }}"
        state: absent
      become: true
      when: ansible_facts.distribution == "Ubuntu"
      with_items:
        - /etc/apt/sources.list.d/cuda.list
        - /etc/apt/sources.list.d/cuda-ubuntu2204-x86_64.list
        - /etc/apt/sources.list.d/nvidia-cuda.list
      tags:
        - install
        - cuda

    - name: Update Apt (only for Ubuntu)
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      when: ansible_facts.distribution == "Ubuntu"
      tags:
        - install
        - core

  tasks:
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/zsh-setup.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/vpn.yml
    - include_tasks: tasks/motif.yml
    - include_tasks: tasks/projects.yml
    - include_tasks: tasks/mise.yml
    - include_tasks: tasks/code.yml
    - include_tasks: tasks/git-setup.yml
    - include_tasks: tasks/personal.yml
    - include_tasks: tasks/cuda.yml
    - include_tasks: tasks/models.yml
    - include_tasks: tasks/utility-repos.yml
    - include_tasks: tasks/llama.yml
    - include_tasks: tasks/rider.yml
