#!/usr/bin/env bash

# Check if Ansible is installed, install if not
if ! command -v ansible-playbook &> /dev/null; then
    echo "Installing Ansible..."
    sudo apt update
    sudo apt install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt install -y ansible
fi

# Run the playbook with password prompts
ansible-playbook local.yml --ask-become-pass --vault-password-file="key/ansible" "$@"
