- name: Install controller utilities (Ubuntu)
  apt:
    name:
      - evtest
    state: present
    update_cache: true
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers

- name: Install xpadneo (Xbox Wireless Controller over Bluetooth) on Ubuntu
  apt:
    name:
      - dkms
      - linux-headers-generic
      - bluetooth
      - bluez
      - bluez-tools
    state: present
    update_cache: true
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Ensure Bluetooth stack present (Ubuntu)
  apt:
    name:
      - bluetooth
      - bluez
      - bluez-tools
    state: present
    update_cache: true
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Clone xpadneo source (Ubuntu)
  ansible.builtin.git:
    repo: https://github.com/atar-axis/xpadneo.git
    dest: /usr/src/xpadneo
    version: master
    update: true
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Check if xpadneo DKMS module exists (Ubuntu)
  ansible.builtin.shell: |
    dkms status hid-xpadneo
  register: dkms_status
  failed_when: false
  changed_when: false
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Install xpadneo via DKMS (Ubuntu)
  ansible.builtin.shell: |
    bash -lc 'set -euo pipefail; make install'
  args:
    chdir: /usr/src/xpadneo
  become: true
  when: ansible_facts.distribution == "Ubuntu" and dkms_status.rc != 0
  tags:
    - install
    - controllers
    - xpadneo

- name: Build DKMS module for current kernel (Ubuntu)
  ansible.builtin.shell: |
    dkms build -m hid-xpadneo -v v0.9-226-ga16acb0 -k {{ ansible_kernel }}
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Install DKMS module for current kernel (Ubuntu)
  ansible.builtin.shell: |
    dkms install -m hid-xpadneo -v v0.9-226-ga16acb0 -k {{ ansible_kernel }}
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Load xpadneo kernel module (Ubuntu)
  community.general.modprobe:
    name: hid_xpadneo
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpadneo

- name: Install xpad (USB Xbox controller driver) on Ubuntu
  apt:
    name:
      - linux-modules-extra-{{ ansible_kernel }}
    state: present
    update_cache: true
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpad

- name: Load xpad kernel module (Ubuntu)
  community.general.modprobe:
    name: xpad
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - controllers
    - xpad

- name: Ensure Xbox Elite udev permissions rule present (Ubuntu)
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/99-xbox-elite2.rules
    owner: root
    group: root
    mode: "0644"
    content: |
      SUBSYSTEM=="hidraw", KERNELS=="0005:045E:02FD.*", MODE="0666", TAG+="uaccess"
      SUBSYSTEM=="hidraw", KERNELS=="0005:045E:0B22.*", MODE="0666", TAG+="uaccess"
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  register: xbox_udev_rule
  tags:
    - install
    - controllers
    - xpadneo

- name: Reload udev rules if Xbox Elite rule updated (Ubuntu)
  ansible.builtin.command: udevadm control --reload
  become: true
  when:
    - ansible_facts.distribution == "Ubuntu"
    - xbox_udev_rule is changed
  tags:
    - install
    - controllers
    - xpadneo

- name: Trigger udev for hidraw devices if Xbox Elite rule updated (Ubuntu)
  ansible.builtin.command: udevadm trigger --subsystem-match=hidraw
  become: true
  when:
    - ansible_facts.distribution == "Ubuntu"
    - xbox_udev_rule is changed
  tags:
    - install
    - controllers
    - xpadneo
