- name: Install core utils on dnf-based systems (Fedora)
  dnf:
    name: ["fzf","vim-enhanced","alacritty", "steam"]
  become: true
  when: ansible_facts.distribution == "Fedora" 
  tags:
    - install
    - core 
- name: Enable Copr for lazygit
  become: true
  community.general.copr:
    name: atim/lazygit
  tags:
    - install
    - core 
- name: Install lazygit on dnf-based systems (Fedora)
  dnf:
    name: ["lazygit"]
  become: true
  tags:
    - install
    - core 
- name: Enable Copr for openvpn 
  become: true
  community.general.copr:
    name: dsommers/openvpn3
  tags:
    - install
    - core
    - vpn 
- name: Install openvpn on dnf-based systems (Fedora)
  dnf:
    name: ["openvpn3-client"]
  become: true
  tags:
    - install
    - core 
    - vpn
