- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/ShockleyJE/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Change permission on install file
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/install"
    state: file
    #owner: root
    #group: root
    mode: 0755
  tags:
    - install
    - dotfiles
    - stow
- name: Change permission on ubuntu file
  file:
    path: "{{ lookup('env', 'HOME') }}/.dotfiles/ubuntu"
    state: file
    #owner: root
    #group: root
    mode: 0755
  tags:
    - install
    - dotfiles
    - stow
- name: Init dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow 
