- name: Install Mise
  become_user: "{{ username }}"
  shell: curl https://mise.run | sh 
  tags:
    - install
    - mise
    - core
- name: Trust mise 
  become_user: "{{ username }}"
  shell: zsh -c "mise trust"
  tags:
    - install
    - core
    - mise
- name: Install Mise deps
  become_user: "{{ username }}"
  shell: zsh -c "mise install"
  tags:
    - install
    - core
    - mise
