- name: Install Steam prerequisites (Ubuntu)
  apt:
    name: ["wget", "gdebi-core", "libc6:i386", "libgl1-mesa-dri:i386", "libgl1:i386"]
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Download official Steam package (Ubuntu)
  get_url:
    url: https://cdn.akamai.steamstatic.com/client/installer/steam.deb
    dest: /tmp/steam.deb
    mode: '0644'
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Install Steam from official .deb package (Ubuntu)
  apt:
    deb: /tmp/steam.deb
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Clean up Steam installer file
  file:
    path: /tmp/steam.deb
    state: absent
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Install Steam from repositories (Fedora)
  dnf:
    name: steam
    state: present
  become: true
  when: ansible_facts.distribution == "Fedora"
  tags:
    - install
    - gaming
    - steam
