- name: Install Steam prerequisites (Ubuntu)
  apt:
    name: ["wget", "gdebi-core", "libc6:i386", "libgl1-mesa-dri:i386", "libgl1:i386"]
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Download official Steam package (Ubuntu)
  get_url:
    url: https://cdn.akamai.steamstatic.com/client/installer/steam.deb
    dest: /tmp/steam.deb
    mode: '0644'
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Install Steam from official .deb package (Ubuntu)
  apt:
    deb: /tmp/steam.deb
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Clean up Steam installer file
  file:
    path: /tmp/steam.deb
    state: absent
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - gaming
    - steam

- name: Install Steam from repositories (Fedora)
  dnf:
    name: steam
    state: present
  become: true
  when: ansible_facts.distribution == "Fedora"
  tags:
    - install
    - gaming
    - steam

- name: Download and install Signal's official GPG key
  get_url:
    url: https://updates.signal.org/desktop/apt/keys.asc
    dest: /tmp/signal-key.asc
    mode: '0644'
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal

- name: Convert GPG key to keyring format
  shell: |
    gpg --dearmor < /tmp/signal-key.asc > /usr/share/keyrings/signal-desktop-keyring.gpg
  args:
    creates: /usr/share/keyrings/signal-desktop-keyring.gpg
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal

- name: Download Signal repository sources file
  get_url:
    url: https://updates.signal.org/static/desktop/apt/signal-desktop.sources
    dest: /etc/apt/sources.list.d/signal-desktop.sources
    mode: '0644'
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal

- name: Update package database
  apt:
    update_cache: yes
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal

- name: Install Signal Desktop
  apt:
    name: signal-desktop
    state: present
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal

- name: Clean up Signal GPG key file
  file:
    path: /tmp/signal-key.asc
    state: absent
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - communication
    - signal
