- name: Ensure prj directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/prj"
  register: prj_stat
  tags:
    - install
    - prj

- name: Cloning dev-environment (only if not present)
  git:
    repo: 'https://github.com/ShockleyJE/dev-environment.git'
    dest: "{{ lookup('env', 'HOME') }}/prj/dev-environment"
    version: main
    recursive: yes
    accept_hostkey: yes
    update: yes
  when: prj_stat.stat.exists == False
  tags:
    - install
    - prj

- name: Ensure prj directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/prj/ambr-client"
  register: prj_stat
  tags:
    - install
    - prj

- name: Cloning ambr client
  git:
    repo: 'git@gitlab.com:ambr1/ambr-client.git'
    dest: "{{ lookup('env', 'HOME') }}/prj/ambr-client"
    version: main
    recursive: yes
    accept_hostkey: yes
    update: yes
  when: prj_stat.stat.exists == False
  tags:
    - install
    - prj

- name: Ensure prj directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/prj/ambr-data-service"
  register: prj_stat
  tags:
    - install
    - prj

- name: Cloning ambr data service
  git:
    repo: 'git@gitlab.com:ambr1/ambr-data-service.git'
    dest: "{{ lookup('env', 'HOME') }}/prj/ambr-data-service"
    version: master 
    recursive: yes
    accept_hostkey: yes
    update: yes
  when: prj_stat.stat.exists == False
  tags:
    - install
    - prj

- name: Ensure prj directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/prj/obsidian"
  register: prj_stat
  tags:
    - install
    - prj

- name: Cloning ambr data service
  git:
    repo: 'git@github.com:ShockleyJE/obsidian.git'
    dest: "{{ lookup('env', 'HOME') }}/prj/obsidian"
    version: master 
    recursive: yes
    accept_hostkey: yes
    update: yes
  when: prj_stat.stat.exists == False
  tags:
    - install
    - prj

- name: Ensure prj directory exists
  stat:
    path: "{{ lookup('env', 'HOME') }}/prj/openfga-backup"
  register: prj_stat
  tags:
    - install
    - prj

- name: Cloning openfga-backup
  git:
    repo: 'git@gitlab.com:ambr1/platform-utilities/openfga-backup.git'
    dest: "{{ lookup('env', 'HOME') }}/prj/openfga-backup"
    version: main 
    recursive: yes
    accept_hostkey: yes
    update: yes
  when: prj_stat.stat.exists == False
  tags:
    - install
    - prj