#- name: Ensure .ssh directory exists.
#  file: 
#    dest: "{{ dest_key | dirname }}"
#    mode: 0700 
#    owner: user 
#    state: directory
#- name: Install ssh key
#  copy: 
#    src: "{{ source_key }}"
#    dest: "{{ dest_key }}"
#    mode: 0600
#    owner: "{{ username }}"
- name: Ensure .openvpn directory exists.
  file:
    dest: "~/.openvpn"
    mode: 0700
    state: directory
  tags:
    - vpn 
    - install
- name: Install openvpn config 
  copy:
    src: "./motif/james_desktop.ovpn"
    dest: "~/.openvpn/james_desktop.ovpn"
    mode: 0600
  tags:
    - vpn
    - install
- name: Activate openvpn config
  become_user: "{{ username }}"
  shell: zsh -c "openvpn3 config-import --config ~/.openvpn/james_desktop.ovpn"
  tags:
    - install
    - core
