- name: Install ZSH on apt-based systems
  apt:
    name: zsh
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install ZSH on dnf-based systems (Fedora)
  dnf:
    name: zsh
  become: true
  when: ansible_facts.distribution == "Fedora" 
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install additional wares (Fedora)
  dnf:
    name: which
  become: true
  when: ansible_facts.distribution == "Fedora" 
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install additional wares (Ubuntu)
  apt:
    name: ["which", "curl"]
  become: true
  when: ansible_facts.distribution == "Ubuntu"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Change shell to zsh
  shell: chsh -s $(which zsh) {{ username }}
  become: true
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Check that oh-my-zsh exists
  stat:
    path: /home/{{ username }}/.oh-my-zsh
  register: oh_my_stats
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer --unattended
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
  when: oh_my_stats.stat.exists == False
  become_user: "{{ username }}"

- name: Delete default .zshrc 
  file:
    path: /home/{{ username }}/.zshrc
    state: absent
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
  when: oh_my_stats.stat.exists == False

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "/home/{{ username }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  become_user: "{{ username }}"
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
